version: '2'
services:
    base:
        image: node:latest
        volumes:
            # A use of “external volume” instead of the local volume now is isolated completely from local.
            - nodemodules:/usr/src/app/client/node_modules
            # We mount our current directory . to /usr/src/app/client in the container.
            - .:/usr/src/app/client
        # We need to tell docker in what directory did we put the code in.
        working_dir: /usr/src/app/client
    install:
        extends:
            service: base
        command: yarn install
volumes:
    nodemodules:
        external: true
